### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by AnderssonPeter** [kaa/nlog.targets.lumberjack#3]
I have this simple console program (.net 4.5.2)

Module1.vb:
```
Imports NLog

Module Module1
    Dim logger As Logger = LogManager.GetCurrentClassLogger()
    Sub Main()
        Console.WriteLine("What do you want to do:")
        Console.WriteLine("1. Write message")
        Console.WriteLine("2. Write message with exception")
        Console.WriteLine("3. Write message with properties")
        Console.WriteLine("4. Write message with exception and properties")
        Dim type As Char = Console.ReadKey().KeyChar

        Dim includeException As Boolean = (type = "2"c OrElse type = "4")
        Dim includeProperties As Boolean = (type = "3"c OrElse type = "4")
        Console.WriteLine()
        Dim properties As Dictionary(Of String, String)
        If (includeProperties) Then
            properties = New Dictionary(Of String, String)()
            While (True)
                Console.Write("Property name (Emtpy to stop):")
                Dim propertyName As String = Console.ReadLine()
                If (String.IsNullOrEmpty(propertyName)) Then
                    Exit While
                End If
                Console.Write("Property value: ")
                Dim propertyValue As String = Console.ReadLine()
                properties.Add(propertyName, propertyValue)
            End While
        End If

        Dim exception As Exception
        If (includeException) Then
            Try
                Throw New InvalidOperationException("Some sort of exception")
            Catch ex As Exception
                exception = ex
            End Try
        End If

        Console.Write("Message: ")
        Dim message = Console.ReadLine()

        Console.WriteLine("Level: ")
        For Each logLevel In NLog.LogLevel.AllLevels
            Console.WriteLine($"{logLevel.Ordinal} {logLevel.Name}")
        Next
        Dim levelChar As Char = Console.ReadKey().KeyChar

        Console.WriteLine()
        Dim selectedLogLevel As LogLevel = Nothing
        For Each logLevel In NLog.LogLevel.AllLevels
            If (logLevel.Ordinal = Integer.Parse(levelChar)) Then
                selectedLogLevel = logLevel
            End If
        Next
        Dim logEvent = New LogEventInfo(selectedLogLevel, logger.Name, message)
        If (exception IsNot Nothing) Then
            logEvent.Exception = exception
        End If
        If (properties IsNot Nothing) Then
            For Each key In properties.Keys
                logEvent.Properties.Add(key, properties(key))
            Next
        End If
        logger.Log(logEvent)


        Console.WriteLine("Press any key to close")
        Console.ReadKey()
    End Sub

End Module
```
NLog.config:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" throwExceptions="true">
  <extensions>
    <add assembly="NLog.Targets.Lumberjack" />
  </extensions>
  <targets>
    <target name="logstash" xsi:type="Lumberjack" host="127.0.0.1" port="5000" layout="${message}"/>
    <target name="console" xsi:type="ColoredConsole" />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="logstash"/>
    <logger name="*" minlevel="Trace" writeTo="console"/>
  </rules>
</nlog>
```

When it closes it gets a 
```
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in NLog.dll
Additional information: Object reference not set to an instance of an object.
```
Stacktrace:
```
   at NLog.Targets.Lumberjack.LumberjackTarget.CloseTarget()
   at NLog.Targets.Target.Close()
   at NLog.Targets.Target.NLog.Internal.ISupportsInitialize.Close()
   at NLog.Config.LoggingConfiguration.Close()
   at NLog.LogFactory.set_Configuration(LoggingConfiguration value)
   at NLog.LogManager.TurnOffLogging(Object sender, EventArgs args)
   at NLog.Internal.Fakeables.AppDomainWrapper.OnProcessExit(Object sender, Even
tArgs eventArgs)
```

This only happens when i use Lumberjack.
NLog: 4.3.10
NLog.Targets.Lumberjack: 1.0.2

Also there is currently nothing listening on port `127.0.0.1:5000` but that should not lead to a null reference exception when closing the program if it should crash then its when trying to log.

**Comment by kaa** [comment]
Thanks for an excellent and detailed bug report 👍 

I'll have a look into it more as soon as I have time but at first glance it seems like a simple mistake on my part. 

If you haven't sent any message to your logstash server, since there is no server listening, then there is no stream open when the target tries to [close it on line 59](https://github.com/kaa/nlog.targets.lumberjack/blob/master/NLog.Targets.Lumberjack/LumberjackTarget.cs#L59). I'll try to push an update during the day.

**Comment by kaa** [comment]
The fix is now also updated on nuget, thanks again for the report.

https://www.nuget.org/packages/NLog.Targets.Lumberjack/1.0.4
